#CREATE BANK MASTER AND TRANSACTION TABLES
CREATE TABLE BANK_MASTER (
NAME               VARCHAR(32),
BALANCE				DOUBLE CHECK(BALANCE>1000),
CONSTRAINT BM_PK PRIMARY KEY (NAME));


CREATE TABLE `BANK_TRANSACTION`(
`NAME` VARCHAR(32) NOT NULL,
`AMOUNT` DOUBLE, 
`TYPE` CHAR(1), 
`DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
CONSTRAINT FK_BM FOREIGN KEY (`NAME`) REFERENCES `BANK_MASTER`(`NAME`));


#TRIGGER FOR BANK_MASTER BALANCE
DELIMITER //
DROP TRIGGER IF EXISTS CHECK_BALANCE //
CREATE TRIGGER CHECK_BALANCE BEFORE INSERT ON BANK_MASTER
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.BALANCE < 1000 THEN
        SET msg = CONCAT('BALANCE ERROR: Trying to insert a insufficient value in bank: ', CAST(NEW.BALANCE AS CHAR));
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;

#transaction type cheack trigger
DELIMITER //
DROP TRIGGER IF EXISTS TXN_TYPE //
CREATE TRIGGER TXN_TYPE BEFORE INSERT ON BANK_TRANSACTION
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.TYPE NOT IN ('W','D') THEN
        SET msg = CONCAT('TXN ERROR: invalid type: ', CAST(NEW.TYPE AS CHAR));
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;


#transaction sync trigger
DELIMITER //
DROP TRIGGER IF EXISTS TXN_SYNC //
CREATE TRIGGER TXN_SYNC AFTER INSERT ON BANK_TRANSACTION
FOR EACH ROW
BEGINs
    IF NEW.TYPE LIKE 'W' THEN
        UPDATE bank_master
        SET BALANCE = (BALANCE - NEW.AMOUNT)
        WHERE NAME = NEW.NAME;
    END IF;
    
    IF NEW.TYPE LIKE 'D' THEN
        UPDATE bank_master
        SET BALANCE = (BALANCE + NEW.AMOUNT)
        WHERE NAME = NEW.NAME;
    END IF;
    
END
//

DELIMITER ;



INSERT INTO BANK_MASTER VALUES("vipul",5000);
INSERT INTO BANK_TRANSACTION VALUES("vipul",200.67,'W',CURDATE());

drop table bank_master
drop table bank_transaction