#CREATE master AND merchant TABLES
CREATE TABLE MERCHANT (
NAME               VARCHAR(32),
BALANCE				DOUBLE,
CONSTRAINT MERC_PK PRIMARY KEY (NAME));

CREATE TABLE CUSTOMER (
NAME               VARCHAR(32),
BALANCE				DOUBLE CHECK(BALANCE>500),
CONSTRAINT CUST_PK PRIMARY KEY (NAME));

#TRIGGER FOR customer BALANCE
DELIMITER //
DROP TRIGGER IF EXISTS CUST_BALANCE //
CREATE TRIGGER CUST_BALANCE BEFORE INSERT ON CUSTOMER
FOR EACH ROW
BEGIN
    DECLARE MSG VARCHAR(128);
    IF NEW.BALANCE < 500 THEN
        SET msg = CONCAT('BALANCE ERROR: insufficient balance: ', CAST(NEW.BALANCE AS CHAR));
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;