INSERT INTO MERCHANT VALUES('Merc',500000);
INSERT INTO CUSTOMER VALUES('Vipul',5000);

update customer
set balance = 5000
where name = 'vipul';

DELIMITER //
DROP TRIGGER IF EXISTS UPDATE_CUST_BALANCE //
CREATE TRIGGER UPDATE_CUST_BALANCE BEFORE UPDATE ON CUSTOMER
FOR EACH ROW
BEGIN
	 DECLARE MSG VARCHAR(128);
    IF NEW.BALANCE < 1000 THEN
        SET MSG = CONCAT('BALANCE ERROR: Trying to insert a insufficient value in bank: ', CAST(NEW.BALANCE AS CHAR));
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = MSG;
    END IF;
END
//

DELIMITER ;

select * from CUSTOMER;
select * from MERCHANT;
