var data = [
{ id:"1",
text:"question1",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans1"},
{ id:"2",
text:"question2",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans2"},
{ id:"3",
text:"question3",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans3"},
{ id:"4",
text:"question4",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans4"},
{ id:"5",
text:"question5",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans1"},
{ id:"6",
text:"question6",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans2"},
{ id:"7",
text:"question7",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans3"},
{ id:"8",
text:"question8",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans4"},
{ id:"9",
text:"question9",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans2"},
{ id:"10",
text:"question10",
options:{a:"ans1",b:"ans2",c:"ans3",d:"ans4"}, 
answer:"ans1"}
];